## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [6]:
# 1. Import the WeatherPy_database.csv file. 
path = "Weather_Database/WeatherPy_Database.csv"
city_data_df = pd.read_csv(path)
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,0,Touros,BR,-5.1989,-35.4608,88.70,62,8,15.08,clear sky
1,1,Cidreira,BR,-30.1811,-50.2056,75.33,71,6,9.69,clear sky
2,2,Hilo,US,19.7297,-155.0900,75.27,48,75,4.61,broken clouds
3,3,Atuona,PF,-9.8000,-139.0333,78.67,78,30,18.86,scattered clouds
4,4,Cape Town,ZA,-33.9258,18.4232,68.34,73,100,3.00,overcast clouds

In [11]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 85
What is the maximum temperature you would like for your trip? 95

In [12]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
result_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]

In [13]:
# 4a. Determine if there are any empty rows.
result_df.count() #Find count

City_ID        46
City           46
Country        46
Lat            46
Lng            46
Max Temp       46
Humidity       46
Cloudiness     46
Wind Speed     46
Description    46
dtype: int64

In [14]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = result_df.dropna(how='all',axis=0) #Drop NA rows
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,0,Touros,BR,-5.1989,-35.4608,88.70,62,8,15.08,clear sky
49,49,Vila Velha,BR,-20.3297,-40.2925,85.95,76,40,15.99,scattered clouds
53,53,Aquiraz,BR,-3.9014,-38.3911,91.22,55,48,13.71,scattered clouds
87,87,Santa Maria,BR,-29.6842,-53.8069,94.37,28,46,3.29,scattered clouds
88,88,Acajutla,SV,13.5928,-89.8275,86.47,58,11,9.26,few clouds
102,102,Dzilam Gonzalez,MX,21.2833,-88.9333,88.00,47,22,5.46,few clouds
112,112,Salinopolis,BR,-0.6136,-47.3561,85.57,66,54,13.56,broken clouds
144,144,Borba,BR,-4.3878,-59.5939,87.67,68,100,4.25,overcast clouds
160,160,Sardinata,CO,8.0829,-72.8007,85.68,58,95,5.48,overcast clouds
178,178,Maldonado,UY,-34.6667,-54.9167,87.19,44,43,13.31,scattered clouds
187,187,Arraial Do Cabo,BR,-22.9661,-42.0278,87.76,62,0,11.50,clear sky
241,241,Sao Joao Da Barra,BR,-21.6403,-41.0511,86.09,80,77,18.41,broken clouds
324,324,Santa Cruz Del Sur,CU,20.7147,-77.9956,87.21,54,1,9.73,moderate rain
339,339,Tucuman,AR,-26.8241,-65.2226,93.20,49,40,3.44,scattered clouds
341,341,Acapulco,MX,16.8634,-99.8901,87.62,66,1,2.30,clear sky
343,343,Porto Novo,BJ,6.4965,2.6036,85.82,76,58,9.06,broken clouds
344,344,Botro,CI,7.8525,-5.3106,86.07,31,75,1.14,broken clouds
346,346,Gibara,CU,21.1097,-76.1317,88.92,59,7,16.02,clear sky
354,354,Nisia Floresta,BR,-6.0911,-35.2086,88.61,54,41,13.27,scattered clouds
362,362,Palmas Bellas,PA,9.2319,-80.0867,88.34,73,23,10.71,few clouds
385,385,Nouakchott,MR,18.0858,-15.9785,89.53,27,62,10.11,broken clouds
395,395,Puerto Narino,CO,-3.7703,-70.3831,89.55,74,93,2.75,overcast clouds
397,397,San Carlos Del Zulia,VE,9.0000,-71.9135,89.89,47,63,4.81,broken clouds
399,399,Trairi,BR,-3.2778,-39.2689,87.60,55,50,16.13,scattered clouds
409,409,Nioro,GM,13.3500,-15.7500,92.70,21,19,4.38,few clouds
411,411,Itarema,BR,-2.9248,-39.9167,87.21,59,82,19.51,broken clouds
413,413,Oranjestad,AW,12.5240,-70.0270,85.95,70,40,4.00,scattered clouds
415,415,Karratha,AU,-20.7377,116.8463,90.09,22,2,12.48,clear sky
444,444,Natal,BR,-5.7950,-35.2094,88.45,70,40,18.41,scattered clouds
452,452,Champerico,GT,14.3000,-91.9167,91.94,65,1,7.09,clear sky
456,456,Puerto El Triunfo,SV,13.2833,-88.5500,92.26,53,0,7.90,clear sky
458,458,Itaituba,BR,-4.2761,-55.9836,91.56,55,40,5.75,scattered clouds
459,459,Cururupu,BR,-1.8283,-44.8683,88.66,55,80,8.28,broken clouds
492,492,Arenal,CO,8.4593,-73.9433,91.38,44,69,5.59,broken clouds
513,513,Intipuca,SV,13.1969,-88.0544,91.29,45,0,4.79,clear sky
534,534,Lago Da Pedra,BR,-4.3333,-45.1667,92.43,48,86,3.58,overcast clouds
539,539,Pochutla,MX,15.7432,-96.4661,93.02,48,1,7.14,clear sky
550,550,Segou,ML,13.4317,-6.2157,86.04,10,100,6.51,overcast clouds
556,556,Lethem,GY,3.3803,-59.7968,88.25,56,97,10.69,light rain
558,558,Maceio,BR,-9.6658,-35.7353,89.04,55,40,16.11,scattered clouds
597,597,Venice,US,27.0998,-82.4543,85.26,73,1,8.05,clear sky
598,598,Mayor Pablo Lagerenza,PY,-19.9309,-60.7718,92.08,45,100,11.99,overcast clouds
599,599,Sagua La Grande,CU,22.8067,-80.0756,85.19,62,16,12.88,few clouds
629,629,Puerto Carreno,CO,6.1890,-67.4859,89.58,58,40,13.80,scattered clouds
662,662,West Bay,KY,19.3667,-81.4167,85.06,76,20,1.99,few clouds
668,668,Seminole,US,28.7086,-81.2081,86.43,71,40,5.75,scattered clouds

In [15]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,Touros,BR,88.70,clear sky,-5.1989,-35.4608,
49,Vila Velha,BR,85.95,scattered clouds,-20.3297,-40.2925,
53,Aquiraz,BR,91.22,scattered clouds,-3.9014,-38.3911,
87,Santa Maria,BR,94.37,scattered clouds,-29.6842,-53.8069,
88,Acajutla,SV,86.47,few clouds,13.5928,-89.8275,
102,Dzilam Gonzalez,MX,88.00,few clouds,21.2833,-88.9333,
112,Salinopolis,BR,85.57,broken clouds,-0.6136,-47.3561,
144,Borba,BR,87.67,overcast clouds,-4.3878,-59.5939,
160,Sardinata,CO,85.68,overcast clouds,8.0829,-72.8007,
178,Maldonado,UY,87.19,scattered clouds,-34.6667,-54.9167,

In [16]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row['Lat']
    long = row['Lng']
    params['location'] = f'{lat},{long}'
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotel_names = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_names["results"][0]["name"]
        print("Hotel Found... Adding")
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel not found... skipping.
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel not found... skipping.
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel not found... skipping.
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel not found... skipping.
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding
Hotel Found... Adding

In [17]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.copy()
clean_hotel_df.dropna(inplace=True)
clean_hotel_df = clean_hotel_df[hotel_df["Hotel Name"]!='']
clean_hotel_df.isnull().sum() #Check

City           0
Country        0
Max Temp       0
Description    0
Lat            0
Lng            0
Hotel Name     0
dtype: int64

In [18]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [33]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

#Extra step to export fig as HTML (widget does not work for my pc)
from ipywidgets.embed import embed_minimal_html
embed_minimal_html('export.html', views=[fig])